apiVersion: v1
kind: Template
metadata:
  name: patchman-engine-vmaas-sync

parameters:
  - name: IMAGE_NAMESPACE
    displayName: Image namespace
  - name: IMAGE_TAG
    displayName: Image tag
    value: latest
  - name: VMAAS_ADDRESS
  - name: VMAAS_WS_ADDRESS
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels: { app: patchman-engine }
      name: patchman-engine-vmaas-sync
    spec:
      replicas: 1
      selector:
        app: patchman-engine
        deploymentconfig: patchman-engine-vmaas-sync
      template:
        metadata:
          labels:
            app: patchman-engine
            deploymentconfig: patchman-engine-vmaas-sync
          name: patchman-engine-vmaas-sync
        spec:
          containers:
            - image: ${IMAGE_NAMESPACE}/patchman-engine-app:${IMAGE_TAG}
              imagePullPolicy: Always
              name: patchman-engine-vmaas-sync
              command: [ ./vmaas_sync/entrypoint.sh ]
              resources:
                limits: { cpu: 500m,  memory: 512Mi }
                requests: { cpu: 200m, memory: 512Mi }
              livenessProbe:
                httpGet: { path: /metrics, port: 8083, scheme: HTTP }
              readinessProbe:
                httpGet: { path: /metrics, port: 8083, scheme: HTTP }
              env:
                - { name: LOG_LEVEL, value: debug }
                - { name: LOG_STYLE, value: plain }
                - { name: GIN_MODE, value: release }

                - { name: VMAAS_ADDRESS, value: "${VMAAS_ADDRESS}"}
                - { name: VMAAS_WS_ADDRESS, value: "${VMAAS_WS_ADDRESS}"}

                - { name: DB_TYPE, value: postgres }
                - { name: DB_HOST, value: patchman-engine-database }
                - { name: DB_PORT, value: "5432" }
                - { name: DB_NAME, value: patchman }
                - { name: DB_USER, value: vmaas_sync }
                - name: DB_PASSWD
                  valueFrom:
                    secretKeyRef:
                      name:  patchman-engine-database-passwords
                      key: vmaas-sync-database-password

          dnsPolicy: ClusterFirst
          restartPolicy: Always
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - patchman-engine-vmaas-sync
            from:
              kind: ImageStreamTag
              name: patchman-engine-app:${IMAGE_TAG}
              namespace: ${IMAGE_NAMESPACE}
          type: ImageChange

  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: '8083'
        prometheus.io/scrape: "true"
      labels:
        app: patchman-engine
      name: patchman-engine-vmaas-sync
    spec:
      type: ClusterIP
      ports:
        - name: 8083-tcp
          port: 8083
          protocol: TCP
          targetPort: 8083
      selector:
        app: patchman-engine
        deploymentconfig: patchman-engine-vmaas-sync

